
REVOKE EXECUTE ON FUNCTION public.award_xp(UUID, INTEGER) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.award_xp(UUID, INTEGER) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.award_xp(UUID, INTEGER) FROM anon;
